// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ControlPanel: typeof import('./components/ControlPanel.vue')['default']
    Conversation: typeof import('./components/Conversation.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MessageReceived: typeof import('./components/MessageReceived.vue')['default']
    MessageSent: typeof import('./components/MessageSent.vue')['default']
    PrivateChat: typeof import('./components/PrivateChat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SideBarIcon: typeof import('./components/SideBarIcon.vue')['default']
    SideBarLoginIcon: typeof import('./components/SideBarLoginIcon.vue')['default']
    StreamBar: typeof import('./components/StreamBar.vue')['default']
    'StreamBar (copy)': typeof import('./components/StreamBar (copy).vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}

export {}
