// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddGroupUserModal: typeof import('./components/modals/AddGroupUserModal.vue')['default']
    AddTitleModal: typeof import('./components/modals/AddTitleModal.vue')['default']
    CloseGroupModal: typeof import('./components/modals/CloseGroupModal.vue')['default']
    'CloseGroupModal (copy)': typeof import('./components/modals/CloseGroupModal (copy).vue')['default']
    Community: typeof import('./components/Community.vue')['default']
    CommunityAbout: typeof import('./components/info/CommunityAbout.vue')['default']
    CommunitySettings: typeof import('./components/CommunitySettings.vue')['default']
    ControlPanel: typeof import('./components/ControlPanel.vue')['default']
    Conversation: typeof import('./components/Conversation.vue')['default']
    DefaultModal: typeof import('./components/modals/DefaultModal.vue')['default']
    DeleteMessageModal: typeof import('./components/modals/DeleteMessageModal.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MessageReceived: typeof import('./components/MessageReceived.vue')['default']
    MessageSent: typeof import('./components/MessageSent.vue')['default']
    NewUserMessageModal: typeof import('./components/modals/NewUserMessageModal.vue')['default']
    PermissionSet: typeof import('./components/PermissionSet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SideBarIcon: typeof import('./components/SideBarIcon.vue')['default']
    SideBarLoginIcon: typeof import('./components/SideBarLoginIcon.vue')['default']
    Stream: typeof import('./components/Stream.vue')['default']
    StreamBar: typeof import('./components/StreamBar.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}

export {}
